# -*- coding: utf-8 -*-
"""Plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JoyZUVEp3lWMiChJmem58NEd0Dq66PTE
"""

from google.colab import drive
drive.mount("/content/drive")

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

data = np.load("/content/drive/Shared drives/SIH2020/Dataset/atomdata/cluster_data.npy")
data.shape

plt.rcParams["figure.figsize"] = (8,8)
def x_y_plot(data):
  lat = data[:,0]
  longi = data[:,1]
  plt.plot(lat, longi)

def alt_t_plot(data):
  alt = data[:,2]
  plt.plot(alt)

for i in range(100, 145):       # AEROPLANE LAT-LONG
  x_y_plot(data[i])
plt.show()

for i in range(100, 145):    # AEROPLANE ALTITUDE-TIME
  alt_t_plot(data[i])
plt.show()

drone_lat = data[153,:29,0]    # DRONE LAT-LONG
drone_longi = data[153,:29,1]
plt.plot(drone_lat, drone_longi)

drone_alt = data[153,:29,2]    # DRONE ATITUDE TIME 
plt.plot(drone_alt)

